version: "3.4"

services:
  client:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-client:${MOPS_ENVIRONMENT:-dev}
    ports:
      - "3000:3000"
    restart: always

  server:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-server:${MOPS_ENVIRONMENT:-dev}
    environment:
      ATLASSIAN_USERNAME:
      ATLASSIAN_API_KEY:
    ports:
      - "8080:8080"
    volumes:
      - "nginx-sites:/app/nginx-sites"
    restart: always

  nginx:
    image: nginx
    environment:
      MOPS_ENVIRONMENT:
    depends_on:
      - server
      - client
    volumes:
      - "nginx-sites:/etc/nginx/conf.d"
      - "nginx-certs:/etc/nginx/ssl"
    restart: always

volumes:
  nginx-sites:
  nginx-certs: