version: "3.4"

services:
  client:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-client:${MOPS_ENVIRONMENT:-dev}
    restart: always
  environment:
    MOPS_ENVIRONMENT:

  server:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-server:${MOPS_ENVIRONMENT:-dev}
    environment:
      ATLASSIAN_USERNAME:
      ATLASSIAN_API_KEY:
      MOPS_ENVIRONMENT:
    restart: always

  nginx:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-nginx:${MOPS_ENVIRONMENT:-dev}
    environment:
      MOPS_ENVIRONMENT:
    depends_on:
      - server
      - client
#    volumes:
#      - "nginx-sites:/etc/nginx/conf.d"
#      - "nginx-certs:/etc/nginx/ssl"
    restart: always
    ports:
      - 80:80

volumes:
  nginx-sites:
  nginx-certs: