version: "3.4"

services:
  client:
    build:
      context: ../scrum-board
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      MOPS_ENVIRONMENT: dev
      NODE_ENV: development

  server:
    build: ./
    environment:
      MOPS_ENVIRONMENT: dev
      NODE_ENV: development

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    environment:
      MOPS_ENVIRONMENT: dev
    ports:
      - 8080:80

volumes:
  node_modules: