version: "3.4"

services:
  client:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-client:${MOPS_ENVIRONMENT:-dev}
    restart: always
    environment:
      MOPS_ENVIRONMENT:

  server:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-server:${MOPS_ENVIRONMENT:-dev}
    environment:
      ATLASSIAN_USERNAME:
      ATLASSIAN_API_KEY:
      MOPS_ENVIRONMENT:
      APP_ROOT_URL:
    restart: always

  nginx:
    image: registry.kuracloud.com:5000/adinstruments/scrum-board-nginx:${MOPS_ENVIRONMENT:-dev}
    environment:
      MOPS_ENVIRONMENT:
    depends_on:
      - server
      - client
    volumes:
      - "nginx-certs:/etc/nginx/ssl"
    restart: always
    ports:
      - 80:80

  # This container just grabs the SSL stuff from vault and then goes away
  vault:
    image: vault
    environment:
      VAULT_ADDR: https://vault.kuracloud.com:8200/
      VAULT_TOKEN:
      VAULT_CONTEXT: live
    cap_add:
      - IPC_LOCK
    volumes:
      - "nginx-certs:/etc/nginx/certs"
    command: sh -c "vault read -field=value secret/ssl/adinstruments.com.chained.crt > /etc/nginx/certs/adinstruments.com.crt && vault read -field=value secret/ssl/adinstruments.com.key > /etc/nginx/certs/adinstruments.com.key"

volumes:
  nginx-certs: