FROM nginx
COPY scrumboard.adinstruments.com.conf /etc/nginx/conf.d/default.conf

#COPY *.conf /app/nginx-sites-available/
#COPY ["docker-entrypoint.sh", "/docker-entrypoint.sh"]
#RUN chmod +x /docker-entrypoint.sh
#ENTRYPOINT [ "/docker-entrypoint.sh" ]